### PR TITLE
Suggests text changes to improve tone and readability

### PR DESCRIPTION
**Pull request by willingc**
@Lukasa - These are merely suggestions to improve readability and warm up the tone a bit. Use whatever strikes your fancy.

Cool concept for a project.:cake:

I think that I like the multi-column layout best on a desktop/laptop and the single column on a smartphone or tablet. Personal preference since the multicolumn avoids a scroll.

### CODE REVIEW

**Comment by Lukasa** [comment]
Alright, I really like most of these changes. When I get home today I'll take them, tweak them, and then push them up.

I'm going to stick with the single-column layout though: I feel like it skims better for technical content.

**Comment by willingc** [comment]
Cool. Use whatever works for you ;)

**Comment by Lukasa** [comment]
Merged (with my minor changes in 67486984af2348a2b5340ef7ad91cd7799b983cc). Thanks so much @willingc!

**Comment by Lukasa** [comment]
And the changes are live. =)

**Comment by willingc** [comment]
Looking good. I like the changes you made to the header. :-)

Would you like me to take a look at the about page?

On 08/09/2014 11:09, Cory Benfield wrote:

> And the changes are live. =)
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/Lukasa/mkcert.org/pull/2#issuecomment-54862506.

## 

_Carol Willing_
Developer | Willing Consulting
+1 760 456 9366 | https://willingconsulting.com

**Comment by Lukasa** [comment]
If you'd like to that would be great! :cake:

**Pull request merged**
